# Generated by Django 3.2.9 on 2021-12-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDoc', models.CharField(max_length=50)),
                ('generoDoc', models.CharField(max_length=50)),
                ('anioEstrenoDoc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPeli', models.CharField(max_length=50)),
                ('generoPeli', models.CharField(max_length=50)),
                ('anioEstrenoPeli', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloSerie', models.CharField(max_length=50)),
                ('generoSerie', models.CharField(max_length=50)),
                ('anioEstrenoSerie', models.IntegerField()),
            ],
        ),
    ]
